### ISSUE TITLE
command not found errors

### ISSUE THREAD

**Issue by Lumerica** [TheNoFace/now_downloader#2]
Hi,

I tried to run your script, but I get the following error:

$ ./now.sh -i 766  -o /home/Gyuri/navernow/ -f
./now.sh: line 2: $'\r': command not found
./now.sh: line 21: $'\r': command not found
./now.sh: line 25: $'\r': command not found
./now.sh: line 68: syntax error near unexpected token `$'\r''
'/now.sh: line 68: `function is_not_empty()

**Comment by TheNoFace** [comment]
Seems like the line change mode of the script is set to CRLF, not LF.
